general-knowledge:
  name: "Counties of Ireland"
  format: quiz
  description: This is a test game for Mike to build out the functionality.
  questions:
    connacht: 
      text: 'Which of these is not in Connacht?'
      answers: 
        a: 
          text: "Westmeath"
          is_correct: true
        b: 
          text: "Galway"
          is_correct: false
        c: 
          text: "Mayo"
          is_correct: false
        d: 
          text: "Sligo"
          is_correct: false
    ulster: 
      text: 'Which of these is not in Ulster?'
      answers: 
        a: 
          text: "Cork"
          is_correct: true
        b: 
          text: "Tyrone"
          is_correct: false
        c: 
          text: "Antrim"
          is_correct: false
        d: 
          text: "Donegal"
          is_correct: false
    leinster: 
      text: 'Which of these is not in Leinster?'
      answers: 
        a: 
          text: "Monaghan"
          is_correct: true
        b: 
          text: "Dublin"
          is_correct: false
        c: 
          text: "Meath"
          is_correct: false
        d: 
          text: "Louth"
          is_correct: false
    munster: 
      text: 'Which of these is not in Munster?'
      answers: 
        a: 
          text: "Kilkenny"
          is_correct: true
        b: 
          text: "Clare"
          is_correct: false
        c: 
          text: "Tipperary"
          is_correct: false
        d: 
          text: "Cork"
          is_correct: false
