test-quiz--ciara:
  name: "How well do you know Ciara?"
  format: quiz
  description: Test your knowledge of Ciara by answering questions on her childhood, career, and favourite things.
  questions:
    connacht: 
      text: 'Which of these is not in Connacht?'
      answers: 
        a: 
          text: "Westmeath"
          is_correct: true
        b: 
          text: "Galway"
          is_correct: false
        c: 
          text: "Mayo"
          is_correct: false
        d: 
          text: "Sligo"
          is_correct: false
    ulster: 
      text: 'Which of these is not in Ulster?'
      answers: 
        a: 
          text: "Cork"
          is_correct: true
        b: 
          text: "Tyrone"
          is_correct: false
        c: 
          text: "Antrim"
          is_correct: false
        d: 
          text: "Donegal"
          is_correct: false
    leinster: 
      text: 'Which of these is not in Leinster?'
      answers: 
        a: 
          text: "Monaghan"
          is_correct: true
        b: 
          text: "Dublin"
          is_correct: false
        c: 
          text: "Meath"
          is_correct: false
        d: 
          text: "Louth"
          is_correct: false
    munster: 
      text: 'Which of these is not in Munster?'
      answers: 
        a: 
          text: "Kilkenny"
          is_correct: true
        b: 
          text: "Clare"
          is_correct: false
        c: 
          text: "Tipperary"
          is_correct: false
        d: 
          text: "Cork"
          is_correct: false

test-quiz--mike:
  name: "How well do you know Mike?"
  format: quiz
  description: Test your knowledge of Mike by answering questions on his childhood, career, and favourite things.
  questions:
    connacht: 
      text: 'Which of these is not in Connacht?'
      answers: 
        a: 
          text: "Westmeath"
          is_correct: true
        b: 
          text: "Galway"
          is_correct: false
        c: 
          text: "Mayo"
          is_correct: false
        d: 
          text: "Sligo"
          is_correct: false
    ulster: 
      text: 'Which of these is not in Ulster?'
      answers: 
        a: 
          text: "Cork"
          is_correct: true
        b: 
          text: "Tyrone"
          is_correct: false
        c: 
          text: "Antrim"
          is_correct: false
        d: 
          text: "Donegal"
          is_correct: false
    leinster: 
      text: 'Which of these is not in Leinster?'
      answers: 
        a: 
          text: "Monaghan"
          is_correct: true
        b: 
          text: "Dublin"
          is_correct: false
        c: 
          text: "Meath"
          is_correct: false
        d: 
          text: "Louth"
          is_correct: false
    munster: 
      text: 'Which of these is not in Munster?'
      answers: 
        a: 
          text: "Kilkenny"
          is_correct: true
        b: 
          text: "Clare"
          is_correct: false
        c: 
          text: "Tipperary"
          is_correct: false
        d: 
          text: "Cork"
          is_correct: false

test-quiz--numbers:
  name: "The numbers of Ciara & Mike"
  format: quiz
  description: All of the answers to this quiz are numbers. But which one is the correct one?
  questions:
    connacht: 
      text: 'Which of these is not in Connacht?'
      answers: 
        a: 
          text: "Westmeath"
          is_correct: true
        b: 
          text: "Galway"
          is_correct: false
        c: 
          text: "Mayo"
          is_correct: false
        d: 
          text: "Sligo"
          is_correct: false
    ulster: 
      text: 'Which of these is not in Ulster?'
      answers: 
        a: 
          text: "Cork"
          is_correct: true
        b: 
          text: "Tyrone"
          is_correct: false
        c: 
          text: "Antrim"
          is_correct: false
        d: 
          text: "Donegal"
          is_correct: false
    leinster: 
      text: 'Which of these is not in Leinster?'
      answers: 
        a: 
          text: "Monaghan"
          is_correct: true
        b: 
          text: "Dublin"
          is_correct: false
        c: 
          text: "Meath"
          is_correct: false
        d: 
          text: "Louth"
          is_correct: false
    munster: 
      text: 'Which of these is not in Munster?'
      answers: 
        a: 
          text: "Kilkenny"
          is_correct: true
        b: 
          text: "Clare"
          is_correct: false
        c: 
          text: "Tipperary"
          is_correct: false
        d: 
          text: "Cork"
          is_correct: false
