general-knowledge:
  name: "General Knowledge"
  description: How well do you know Ciara & Mike? Test yourself with this simple ten question multiple choice question game.
  questions:
    q1: 
      text: 'Q1: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false
    q2: 
      text: 'Q2: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B13: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false
    q3: 
      text: 'Q3: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false

memory-lane-mike:
  name: "Memory Lane: Mike"
  description: Take a whirlwind tour through Mike's childhook and answer some simple multiple choice questions.
  questions:
    q1: 
      text: 'Q1: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false
    q2: 
      text: 'Q2: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false
    q3: 
      text: 'Q3: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false

memory-lane-ciara:
  name: "Memory Lane Ciara"
  description: Take a whirlwind tour through Ciara's childhook and answer some simple multiple choice questions.
  questions:
    q1: 
      text: 'Q1: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false
    q2: 
      text: 'Q2: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false
    q3: 
      text: 'Q3: General Knowledge'
      answers: 
        a: 
          text: "Correct Answer"
          is_correct: true
        b: 
          text: "B1: B"
          is_correct: false
        c: 
          text: "C1: C"
          is_correct: false
        d: 
          text: "D1: D"
          is_correct: false